---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: reloader
      version: "1.0.5"
      sourceRef:
        kind: HelmRepository
        name: stakater-reloader
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: false
  values:
    reloader:
      # Use reloader.stakater.com/auto: "true" in annotations
      # to reload after changing sercret or configmap
      reloadStrategy: annotations
