---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stakater-reloader
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://stakater.github.io/stakater-charts
