---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: k6
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/grafana/k6-operator
  ref:
    tag: v0.0.9
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: k6
  namespace: flux-system
spec:
  interval: 10m
  wait: true
  timeout: 5m
  retryInterval: 5m
  prune: true
  force: false
  targetNamespace: supp
  sourceRef:
    kind: GitRepository
    name: k6
  path: "./config/default"
